### ISSUE TITLE
Llevar registro de meetings y toda la info necesaria dentro de la Wiki de GitHub. (Ver consideraciones generales)

### ISSUE THREAD

**Issue by isaias4912** [C4ndela/Trabajo-Final-FullStack-ISPC2022#6]

**Comment by hernanruscica** [comment]
Hola. Quería comentarles que la profe vivíana Guillén, me dijo que pongamos en una página de la wiki, el hecho que me agregaron en este grupo. En la plataforma ya me agrego el profe jeremías al foro del grupo 97. Pero aclaro que lo pongamos también acá.
